using System.Collections;
using System.Collections.Generic;

namespace Interpark.Entity
{
    class SessionInfo
    {
        public string PenaltyScript { get; set; }
        public string RAddr { get; set; }
        public string Addr { get; set; }
        public string GoodsBizName { get; set; }
        public string PlaceName { get; set; }
        public string RName { get; set; }
        public string MemberName { get; set; }
        public IList<string> PriceGradeName { get; set; }
        public string RcptTaxYN { get; set; }
        public string DeliveryOrNot { get; set; }
        public string SmsOrNot { get; set; }
        public string DeliveryEnc { get; set; }
        public string PaymentEnc { get; set; }
        public string OtherSiteGSYN { get; set; }
        public string BizCode { get; set; }
        public string SIDBizCode { get; set; }
        public IList<string> PGType { get; set; }
        public string TypeOfUse { get; set; }
        public string Tiki { get; set; }
        public string BadUserOrNot { get; set; }
        public string ReservedOrNot { get; set; }
        public string Always { get; set; }
        public string HotSaleOrNot { get; set; }
        public string AgreeOrNot { get; set; }
        public string UserInfoOrNot { get; set; }
        public string SeasonOrNot { get; set; }
        public string PackageOrNot { get; set; }
        public string MobileOrNot { get; set; }
        public string HomeOrNot { get; set; }
        public string SecretGoodsYN { get; set; }
        public string LuckyBagGoodsYN { get; set; }
        public string ISPDiscountOrNot { get; set; }
        public string DiscountOrNot { get; set; }
        public IList<string> DblDiscountOrNot { get; set; }
        public string RHpNo { get; set; }
        public string HpNo { get; set; }
        public string RPhoneNo { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string SSN { get; set; }
        public string MCash_TotalAmt { get; set; }
        public string TmgsOrNot { get; set; }
        public IList<string> SalesPrice { get; set; }
        public string HashPrice { get; set; }
        public string SupplyType { get; set; }
        public string OnlyDeliver { get; set; }
        public string GoodsOption { get; set; }
        public string TMemHash { get; set; }
        public string BankCode { get; set; }
        public IList<string> SeatGradeName { get; set; }
        public string DelyAmt { get; set; }
        public string DelyFee { get; set; }
        public string Delivery { get; set; }
        public string FirstKindOfPayment { get; set; }
        public string TotalAmt { get; set; }
        public string FirstSettleAmt { get; set; }
        public string EndDate { get; set; }
        public string StartDate { get; set; }
        public string PlayDate { get; set; }
        public string CancelableDate { get; set; }
        public string BookingEndDate { get; set; }
        public string OnlineDate { get; set; }
        public string CartID { get; set; }
        public string GroupName { get; set; }
        public string TotalUseAmt { get; set; }
        public string TicketCnt { get; set; }
        public string TicketAmt { get; set; }
        public string DiscountAmt { get; set; }
        public string CartIDSeq { get; set; }
        public string RZipcode { get; set; }
        public string Zipcode { get; set; }
        public string GroupCode { get; set; }
        public string GoodsCode { get; set; }
        public string PlaceCode { get; set; }
        public string RSubAddr { get; set; }
        public string SubAddr { get; set; }
        public string SessionId { get; set; }
        public string PlayTime { get; set; }
        public string DBDay { get; set; }
        public string UseAmt { get; set; }
        public string NoOfTime { get; set; }
        public IList<string> SeatGrade { get; set; }
        public string GoodsBizCode { get; set; }
        public string BizMemberCode { get; set; }
        public string SubCategory { get; set; }
        public string KindOfGoods { get; set; }
        public IList<string> PriceGrade { get; set; }
        public string PlaySeq { get; set; }
        public IList<string> GroupId { get; set; }
        public IList<string> DiscountCode { get; set; }
        public string TikiDiscountCnt { get; set; }
        public string VoucherAmt { get; set; }
        public string ExpressDelyDay { get; set; }
        public string ExpressDelyFee { get; set; }
        public string Coupon_DiscountValue { get; set; }
        public string Coupon_DiscountAmt { get; set; }
        public string DeliveryGiftAmt { get; set; }
        public string MCash_UseAmt { get; set; }
        public string TicketCntTikiDiscount { get; set; }
        public string SecondSettleAmt { get; set; }
        public string useGSPoint { get; set; }
        public IList<string> VoucherSalesPrice { get; set; }
        public IList<string> BlockNo { get; set; }
        public IList<string> Floor { get; set; }
        public IList<string> RowNo { get; set; }
        public IList<string> SeatNo { get; set; }
        public IList<string> VoucherCode { get; set; }
        public IList<string> SeatInfo { get; set; }
        public string TikiGrade { get; set; }
        public string LocOfImage { get; set; }
        public string LmtKindOfSettle { get; set; }
        public string LmtCardIssueCode { get; set; }
        public string LmtSalesYN { get; set; }
        public string KindOfDiscount { get; set; }
        public string DiscountName { get; set; }
        public string DiscountSeq { get; set; }
        public string TikiKindOfDiscount { get; set; }
        public string OtherKindOfDiscount { get; set; }
        public string CardKindOfDiscount { get; set; }
        public string CardKind { get; set; }
        public string CardDiscountKind { get; set; }
        public string CardIssueCode { get; set; }
        public string CardDiscountNo { get; set; }
        public string CardDelivery { get; set; }
        public string Point { get; set; }
        public string PointSeq { get; set; }
        public string PointDiscountAmt { get; set; }
        public string CouponCode { get; set; }
        public string CouponName { get; set; }
        public string Coupon_TypeOfPay { get; set; }
        public string Coupon_ChargeInfo { get; set; }
        public string Coupon_DblDiscountOrNot { get; set; }
        public string DeliveryGift { get; set; }
        public string MCash_TelKind { get; set; }
        public string MCash_No { get; set; }
        public string MCash_SSN { get; set; }
        public string MCash_Smsval { get; set; }
        public string MCash_Phoneid { get; set; }
        public string MCash_Traid { get; set; }
        public string KindOfSettle { get; set; }
        public string DoubleChecked { get; set; }
        public string PaymentDouble { get; set; }
        public string TotGiftSttledAmt { get; set; }
        public string SecondKindOfPayment { get; set; }
        public string KindOfCard { get; set; }
        public string DiscountCard { get; set; }
        public string CardNo { get; set; }
        public string ValidInfo { get; set; }
        public string CardSSN { get; set; }
        public string CardPWD { get; set; }
        public string HalbuMonth { get; set; }
        public string LGPoint { get; set; }
        public string WooriPoint { get; set; }
        public string CitiPoint { get; set; }
        public string KBPoint { get; set; }
        public string MPoint { get; set; }
        public string SSPoint { get; set; }
        public string KEBPoint { get; set; }
        public string CultrueUser { get; set; }
        public string HappyUser { get; set; }
        public string FirstSubKindOfPayment { get; set; }
        public string PayDiscountCode { get; set; }
        public string Encrypted { get; set; }
        public string RN { get; set; }
        public string IspCardCode { get; set; }
        public string CardCode { get; set; }
        public string CardQuota { get; set; }
        public string BearsNumber { get; set; }
        public string GSPwd { get; set; }
        public string GSCardNo { get; set; }
        public string GSType { get; set; }
        public string GSPointUseYN { get; set; }
        public string GSPointSaveYN { get; set; }
        public string GSPointCheckYN { get; set; }
        public string OtherSiteGSCardNo { get; set; }
        public string OtherSiteGSPwd { get; set; }
        public string expoRecommander { get; set; }
        public string expoRecOrg { get; set; }
        public string expoName { get; set; }
        public string expoImg { get; set; }
        public string FCSeasonNo { get; set; }
        public string DiscountSalesPrice { get; set; }
        
        /*
        public string Tiki { get; set; }
        public string TikiGrade { get; set; }
        public string GroupCode { get; set; }
        
        public string BizCode { get; set; }
        public string BizMemberCode { get; set; }
        public string SessionId { get; set; }

        public string PlayDate { get; set; }
        public string PlaySeq { get; set; }
        
        public string SIDBizCode { get; set; }
        public string FCSNo { get; set; }
        
        public string CancelableDate { get; set; }
        */
        
    }
}
